#!/usr/bin/env python3
"""Build codex/spellbook.json from plan/plan-data.json + plan/racials.json.

Run from the repo root. Also prunes stale classicOnly entries from
plan-data.json: a spell the book now carries (client-mined) cannot also be
"not in the Forever demo book".
"""
import json, re, collections

pd = json.load(open("plan/plan-data.json"))
rc = json.load(open("plan/racials.json"))

# --- prune classicOnly rows contradicted by the book itself -------------
pruned = []
for cls in pd["classes"]:
    bk = cls["book"]
    names = set()
    for t in bk["tabs"]:
        for s in t["spells"]: names.add(s[0])
    for s in bk.get("general", []): names.add(s[0])
    keep = []
    for co in bk.get("classicOnly", []):
        if co["n"] in names:
            pruned.append((cls["cls"], co["n"]))
        else:
            keep.append(co)
    bk["classicOnly"] = keep
if pruned:
    json.dump(pd, open("plan/plan-data.json", "w"), ensure_ascii=False, separators=(",", ":"))
    print("pruned stale classicOnly:", len(pruned), pruned[:6], "...")

spells, talents, racials = [], [], []
for cls in pd["classes"]:
    cname = cls["cls"].capitalize()
    bk = cls["book"]
    seen = set()
    rows = []
    for t in bk["tabs"]:
        for s in t["spells"]: rows.append((s[0], s[1], t["name"]))
    for s in bk.get("general", []): rows.append((s[0], s[1], "General"))
    for n, tag, tab in rows:
        if n in seen: continue
        seen.add(n)
        hdr = bk.get("hdr", {}).get(n, [])
        lvl = None
        for pair in hdr:
            m = re.match(r"Level (\d+)$", (pair[0] or "").strip())
            if m: lvl = int(m.group(1)); break
        src = bk.get("src", {}).get(n)
        if src is None: src = "basic"
        if src == "basic" and lvl is None: lvl = 1
        cmp = bk.get("cmp", {}).get(n) or {}
        e = {"n": n, "c": cname, "tab": tab, "lvl": lvl, "src": src}
        if tag: e["tag"] = tag
        ic = pd.get("spellIcons", {}).get(n)
        if ic: e["icon"] = ic
        d = bk.get("desc", {}).get(n)
        if d: e["d"] = d
        if cmp.get("s"): e["s"] = cmp["s"]
        if cmp.get("note"): e["note"] = cmp["note"]
        if cmp.get("cl") is not None: e["cl"] = cmp["cl"]
        spells.append(e)
    for co in bk.get("classicOnly", []):
        ic = pd.get("spellIcons", {}).get(co["n"])
        spells.append({"n": co["n"], "c": cname, "tab": "Not in the demo book", "lvl": co.get("lvl"),
                       "src": "classiconly", "d": co.get("note", ""),
                       **({"icon": ic} if ic else {})})
    for tr in cls["trees"]:
        for t in tr["talents"]:
            c = t.get("c") if isinstance(t.get("c"), dict) else {}
            e = {"n": t["n"], "c": cname, "tree": tr["name"], "r": t["r"], "row": t["row"],
                 "icon": t.get("icon"), "d": (t.get("desc") or [""])[0]}
            if c.get("s"): e["s"] = c["s"]
            talents.append(e)

for race, abilities in rc["races"].items():
    for a in abilities:
        racials.append({"n": a["n"], "race": race, "kind": a.get("kind", ""),
                        "icon": a.get("icon"), "d": a.get("tip") or a.get("summary", "")})

out = {
  "note": "Generated by tools/build_spellbook.py from plan/plan-data.json and plan/racials.json. Spell tooltips: beta client 1.60.1.69876 where src=client; sod = SoD wiring with no Forever learn level; classic = Classic placeholder text, demo tooltip not captured; basic = universal demo-book listing; classiconly = Classic spell absent from the Forever demo book. Talents and racials: BlizzCon demo transcription via talentsforever.com export (CC BY 4.0).",
  "spells": spells, "talents": talents, "racials": racials
}
json.dump(out, open("codex/spellbook.json", "w"), ensure_ascii=False, separators=(",", ":"))
print("spells", len(spells), "talents", len(talents), "racials", len(racials))
dupes = [k for k, v in collections.Counter((s["c"], s["n"]) for s in spells).items() if v > 1]
print("remaining same-class dupes:", dupes)
